### ISSUE TITLE
Works in Javascript, broken in PHP

### ISSUE THREAD

**Issue by softwarecreations** [atom/toggle-quotes#60] opened 2018-08-10 09:28 UTC
### Description

My quotes characters are   \"  \'  \`  (without spaces, only shown with spaces here for clarity)
JS files will infinitely cycle some quoted text between the 3 types of quotes. But PHP stops when it gets to \`  `.

### Steps to Reproduce

1. Make 2 new files, set the types to Javascript and PHP respectively (no need to save)
Javascript file contains: `var foo = 'hello';`
PHP file contains: `<?php $foo = 'hello';`
2. Press the bound key for toggle-quotes:toggle (which is Ctrl-" by default) inside the quotes in each file and see that it is broken for PHP.

**Expected behavior:** [What you expect to happen]
The types of quotes should cycle infinitely. Perhaps it's because `` aren't valid quotes in PHP, but who cares, what I'm trying to do is if it's `"` I want to swap to `'`  And if it's ' I want to cycle past ``` to get to `"`

**Actual behavior:** [What actually happens]
PHP files get stuck on ` quotes.

**Reproduces how often:** [What percentage of the time does it reproduce?]
Always 100% of the time the bug is present.

### Versions
Toggle quotes 1.1.1
Atom 1.27.2 but my atom version is irrelevant because this bug has been present forever.

**Comment by rsese** [comment] 2018-10-18 19:54
Thanks for the report - we noticed that this looks like a duplicate of https://github.com/atom/toggle-quotes/issues/51 so you can subscribe there if you'd like.  

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2018-10-18 19:54 UTC
