### ISSUE TITLE
Key binding not working

### ISSUE THREAD

**Issue by kankaristo** [atom/toggle-quotes#23] opened 2015-05-25 14:39 UTC
The key binding is not working with a Finnish/Swedish keyboard layout (on Ubuntu).

I added `ctrl-shift-2`, which works well (`"` is behind `shift-2`). Based on a quick Google search, this would probably fix the key binding on Finnish, Swedish, Norwegian, Danish, Icelandic, Estonian and German keyboards (possibly others).

Could this be added to the list of default key bindings?

**Comment by lee-dohm** [comment] 2015-05-25 16:17
Atom doesn't have a method of setting a key binding for specific regions, so this would consume <kbd>Ctrl+Shift+2</kbd> for everyone. Since there are already issues with too many conflicting key bindings, I would recommend against making this a default.

I think the real solution is fixing https://github.com/atom/atom-keymap/issues/37

**Comment by kankaristo** [comment] 2015-05-25 20:07
I agree that this is only a stopgap solution to a bigger underlying problem.

IMO, it would be best to avoid (not stop using entirely, but avoid) special characters in key bindings. While toggling tree view with `ctrl+\` makes sense on a US keyboard, on a Finnish layout it becomes `ctrl+AltGr++` (`+` is next to `0`), which is a little uncomfortable to use (even if https://github.com/atom/atom-keymap/issues/37 were fixed). In the same way `ctrl+ä` makes sense on a Finnish layout, but is impossible to use on a US layout.

The **real** problem is the Finnish keyboard layout, which is difficult to use anyway, but that's probably not changing any time soon. :)

Should I close the issue? The issue is still there, but the actual problem is with Atom's core, not toggle-quotes.

**Comment by lee-dohm** [comment] 2015-05-25 20:20
> IMO, it would be best to avoid (not stop using entirely, but avoid) special characters in key bindings.

I think that's a pretty good guideline.

> Should I close the issue? The issue is still there, but the actual problem is with Atom's core, not toggle-quotes.

Yes, I think essentially this is a duplicate of atom/atom-keymap#37. Thanks for reporting it though!

**Closed** 2015-05-25 20:47 UTC
