### ISSUE TITLE
No settings?

### ISSUE THREAD

**Issue by matthewwithanm** [atom/toggle-quotes#19] opened 2015-03-27 00:32 UTC
I'd like to update the quotesCharacters setting from #17, but I'm not seeing the settings! It must be something dumb; I feel like I'm going crazy.

I'm running 0.10 and have uninstalled, reinstalled, and restarted many times now.

![screen shot 2015-03-26 at 8 31 13 pm](https://cloud.githubusercontent.com/assets/126263/6859983/280373aa-d3f7-11e4-9c28-e2476dadcaeb.png)

**Comment by lettertwo** [comment] 2015-04-08 19:37
I'm also seeing the same behavior. I manually added the setting to my config:
```cson
  "toggle-quotes":
    quoteCharacters: "\"'`"
```
After that, the setting started showing up in the panel.

**Comment by izuzak** [comment] 2015-04-08 20:39
This is a duplicate of https://github.com/atom/settings-view/issues/356 -- this package [has activationCommands defined](https://github.com/atom/toggle-quotes/blob/a62b2f21ffee9595f64cbf568eccea918626ef18/package.json#L8-L11), so the config settings are not rendered until one of those commands are triggered. I'm going to leave this open and add a blocked label. Thanks for the report!

**Comment by izuzak** [comment] 2015-04-08 20:46
Another approach to solving this for this package would be to just remove the activation commands.

**Comment by izuzak** [comment] 2015-04-13 13:29
https://github.com/atom/settings-view/issues/356 was fixed, so this is fixed as well now. If you build Atom from source -- you should see the fix if you build the latest master. If you're using released versions -- the next release (0.191.0) will have the fix.

**Closed by izuzak** 2015-04-13 13:29 UTC
Labels: blocked, bug, duplicate
