### ISSUE TITLE
Can't toggle quotes if line contains tabs

### ISSUE THREAD

**Issue by fyrebase** [atom/toggle-quotes#27] opened 2015-08-05 23:59 UTC
The toggle quotes command appears to be executing but is not actually toggling the quotes in atom 1.0.4

`<?php my_random_function( 'quoted-string' ) ?>`

I have tried removing the plugin, re-installing and restarting atom.

**Comment by mnquintana** [comment] 2015-08-06 00:00
What keyboard shortcut are you entering? Can you open the keybinding resolver first (<kbd>Ctrl or Cmd-.</kbd>) and enter that shortcut, and post a screenshot of what you see?

**Comment by fyrebase** [comment] 2015-08-06 00:09
I am using `cmd+"`

![screen shot 2015-08-06 at 10 07 14 am](https://cloud.githubusercontent.com/assets/210659/9100863/0471f594-3c23-11e5-98de-f3e6ee8915b5.png)

**Comment by mnquintana** [comment] 2015-08-06 00:11
Thanks for the update! Can you try placing your cursor in that string that won't toggle, and enter <kbd>Cmd-Alt-P</kbd> and take a screenshot of the notification that pops up?

**Comment by fyrebase** [comment] 2015-08-06 00:15
Here you go...

![screen shot 2015-08-06 at 10 15 16 am](https://cloud.githubusercontent.com/assets/210659/9100959/11155a88-3c24-11e5-8391-9145b3344724.png)

**Comment by mnquintana** [comment] 2015-08-06 00:18
Thanks for that! I can reproduce this with toggle-quotes 0.11.1 and Atom 1.0.5-4045b44.

**Comment by fyrebase** [comment] 2015-08-06 00:24
Thanks for digging into it and confirming there is a bug @mnquintana. It stopped working when atom updated, I'm guessing the previous version was 1.0.3

**Comment by mnquintana** [comment] 2015-08-06 00:26
Scratch that, looks like this applies to every language

**Comment by mnquintana** [comment] 2015-08-06 00:37
@fyrebase Actually, can you try restarting / reopening Atom? I just tried that, and it seems to have fixed toggling quotes. If that works for you, then I think this is an issue that comes up only when a new version of toggle-quotes is installed.

**Comment by fyrebase** [comment] 2015-08-06 00:44
Ok... I've restarted and it still doesn't work in this scope...

![screen shot 2015-08-06 at 10 15 16 am](https://cloud.githubusercontent.com/assets/210659/9101280/13fba460-3c28-11e5-8cc2-1e1a42823006.png)

but it does work in this scope...

![screen shot 2015-08-06 at 10 42 58 am](https://cloud.githubusercontent.com/assets/210659/9101283/2148894e-3c28-11e5-9e22-edff88ad90f4.png)

**Comment by fyrebase** [comment] 2015-08-06 00:50
@mnquintana I think I have found the cause. **Tab indents** . Toggle quotes works perfectly when using space indentation, but not when using tabs.

**Comment by tsarapke** [comment] 2015-08-06 08:51
@fyrebase I agree with you. I checked it with rows which have space and tabs indentation. So, if your row contain at least one tab before text - plugin doesn't work for this row.
Checked variants:
* _tab_ __" text "__
* _space_  _tab_ __" text "__

Also, i found another bug. If your text contain tab inside and after himself, after toggle it add double quote to end of your text.
For example:
* _space_  __" te__ _tab_ __xt "__ _tab_

if you toggle quotes, then you will get next result:
* _space_  __' te__ _tab_ __xt\" '__

**Comment by fyrebase** [comment] 2015-08-06 11:11
Thanks for confirming that @tsarapke. I'm hoping it's an easy fix... I like tabs.

**Comment by KnutHelland** [comment] 2015-11-14 19:07
Any news on this issue? Would be fantastic to have a function like _toggle-quotes_, but I'm working on js projects where we use tabs so this package is currently useless for me.

I've investigated it a little. It looks like the problem is eighter here:
```
  range = editor.displayBuffer.bufferRangeForScopeAtPosition('.string.quoted', position)
```
or here:
```
  text = editor.getTextInScreenRange(range)
```
in `toggle-quotes.coffee`.

The `range` returned from displayBuffer is apparently screen coordinates. So when my editor is configured with `editor.tabLength: 4` each tab is counted at `4` columns.

And that makes `text` become wrong.

If I set `editor.tabLength: 1` in config, `toggle-quotes` works perfectly even with tabs.

This is probably very easy to fix for someone who knows the apis well.

**Comment by KnutHelland** [comment] 2015-11-14 22:02
I tried to make a dirty fix for this (https://github.com/KnutHelland/toggle-quotes/commit/3c79225e08f5f0a67c0aaf519dade2e1bcad438a). But that *does not work* when buffer is folded.

I think there is an issue with `bufferRangeForScopeAtPosition`. It apparently returns _screen columns_ and _buffer rows_. There's actually an open issue on it here: https://github.com/atom/atom/issues/8685

**Comment by braver** [comment] 2015-12-15 08:52
If this isn't going to be fixed, it'd be nice to add this to the readme. Entire populations still use tab indents and it's annoying to have to dig into the open issues to figure out why this package doesn't work.

**Comment by justo** [comment] 2016-01-11 16:50
I agree @braver, this seems like a really silly bug that should be mentioned somewhere obvious if it isn't fixable.

**Comment by mnquintana** [comment] 2016-01-11 18:03
@braver @justo Just documented that here: https://github.com/atom/toggle-quotes/blob/master/README.md#toggle-quotes

I dug into this issue earlier today, and I think @KnutHelland's right – the issue lies with `bufferRangeForScopeAtPosition`

**Comment by danielbayley** [comment] 2016-02-08 23:10
I just ran into this problem.

> this seems like a really silly bug that should be mentioned somewhere obvious if it isn't fixable.

Surely it is fixable?

**Comment by lope** [comment] 2016-02-25 09:10
+1

**Comment by jsg2021** [comment] 2016-07-13 16:07
Love to see this fixed! :}

**Comment by lope** [comment] 2016-07-14 13:15
Since making the above comment I've been using this plugin a lot!

I've just adapted to using a tab width of 1 as a workaround for this bug.
It's a little bit tricky/non-obvious to see the level of indentation sometimes, but you get used to it. For the really tricky times you can use the rulerz plugin in combination with the toggle-packages plugin.

**Comment by Aerijo** [comment] 2018-08-11 09:45
@ahallicks I've been trying to reproduce, but the examples in this thread aren't failing for me. Do you have a set of steps I can follow to reliably reproduce that bug in a JS file?

**Comment by Aerijo** [comment] 2018-11-22 08:19
Can anyone confirm if this is still an issue? I've tried reproducing with 
```
var x = {
	a:	{s:"blah"},
		b:	 {s:"blah"}
}
```
(where the spaces are tabs), but it still toggled as expected.

If it is broken, can you provide the text that breaks it?

**Comment by ahallicks** [comment] 2018-11-22 12:30
@Aerijo it's all working fine for me now. Must have been an Atom blip in an old beta version.

**Comment by Aerijo** [comment] 2018-11-22 12:31
Thanks. I'll go ahead and close this, but I'll reopen if anyone else still has the issue.

**Closed by Aerijo** 2018-11-22 12:31 UTC
Labels: bug
