### ISSUE TITLE
Not really working?

### ISSUE THREAD

**Issue by karan** [atom/toggle-quotes#2] opened 2014-03-03 18:01 UTC
Maybe I'm doing something wrong, but this doesn't seem to work for me.

Tried, `cmd+shift+'`, `cntr+shift+'` and all combinations. On Mavericks.

**Comment by pedronauck** [comment] 2015-02-03 04:58
It's kinda weird, but to me I changed this:

```
'atom-workspace':
  'cmd-"': 'toggle-quotes:toggle'
```

by that:

```
'.workspace':
  'cmd-"': 'toggle-quotes:toggle'
```

and now workds perfectly!

**Comment by mafredri** [comment] 2015-02-13 13:25
Unsure if related, but I have the following Puppet code:
```
    exec { "Installing godep for managing Go dependencies":
        command     => "go get github.com/tools/godep",
        environment => ["GOPATH=${workspace}"],
        path        => "/usr/bin",
        creates     => "${workspace}/bin/godep",
        require     => File['/usr/bin/go'],
    }
```
The toggle seems to work with all the assignment lines (=>), but the exec line cannot be converted from double to single quotes. Weird.

**Comment by monkeymonk** [comment] 2015-03-06 12:49
Still not working... any clue ? Also tried to set another keymap but still not working! :'-(

**Comment by Arcanemagus** [comment] 2015-06-01 03:21
I'm seeing this somewhat randomly throughout several files in Atom 0.204.0. Some examples that demonstrate the issue in a completely clean installation that only has the toggle-quotes plugin installed:
```html
<!DOCTYPE html>
<html lang='en'> <!-- Works -->
	<body class='text'></body> <!-- Fails -->
</html>
```
```php
<?php
function f_name() {
	if ($arry['asdf']) { // Fails
        $var = "text"; // Works
	}
}
?>
```
I'm pretty sure that this _isn't_ toggle-quote's that is the problem here, but rather the Atom API calls that are at fault. When debugging the code for this plugin it seems that the calls to `editor.getTextInBufferRange(range);` are returning only parts of the string instead of properly starting with the initial quote character.
With the HTML example no matter the cursor position the text is set to "text'>". Oddly enough when the cursor is between the ' and > Atom still thinks the cursor is within a string.quoted.single.html scope.
The PHP code snippet is similar, the lines that are failing seem to have their range offset by one.

It doesn't seem that the `editor.displayBuffer.bufferRangeForScopeAtPosition()` hack is at fault here since even using the official (but incorrect for multiple cursors according to https://discuss.atom.io/t/multiple-cursor-issues/7369) `editor.getTextInBufferRange(editor.bufferRangeForScopeAtCursor('string.quoted'))` returns the "off-by-one" text selection.

As I'm somewhat new to Atom I'm not exactly sure _where_ in Atom this could be getting screwed up, but hopefully this information can point somebody in the right direction.

**Comment by nathansobo** [comment] 2015-06-01 18:30
![toggle-quotes](https://cloud.githubusercontent.com/assets/1789/7920076/cbb38b32-089c-11e5-9862-41bbc8a7a1f0.gif)

I'm having trouble reproducing this on master (which includes everything in 0.204.0). As you can see in this gif, I'm able to toggle quotes in the first example.

**Comment by Arcanemagus** [comment] 2015-06-01 18:39
Interestingly it works on my work computer (Win7x64, Atom 0.204.0), but but is failing on my home computer (Win8.1x64, Atom 0.204.0) and a Win10 VM I installed a fresh copy of Atom on. All see if I can figure out what the differences are later today.

**Comment by Arcanemagus** [comment] 2015-06-02 16:52
This seems to be a somewhat random issue, both of the above snippets work on both of my computers now :unamused:.

Currently at least the following snippet is showing the issue on both my work and home computers, as well as a completely blank profile (with just this plugin):
```php
<?php
function get_hist($attr) {
	$max = $bounds[0]['max_val'];
}
?>
```

**Comment by Arcanemagus** [comment] 2015-07-02 22:12
I'm unable to reproduce this issue on any of my 3 installations of Atom as of 1.0.0. Is anyone else still seeing this issue?

**Comment by jaredmoody** [comment] 2015-07-02 22:51
:+1: I'm no longer seeing this issue on 1.0.0

**Comment by 50Wliu** [comment] 2015-07-02 23:46
Ok, I'm going to close this for now.
If anyone can still reproduce this issue on 1.0.0+, please comment here!

**Closed by 50Wliu** 2015-07-02 23:46 UTC
Labels: bug

**Comment by ipaintcode** [comment] 2016-06-14 18:23
I just installed this package and it's mostly not working on Atom 1.8.0 (OS X 10.11.5) with the latest toggle quotes. Ruby files it works but JavaScript, CSS, HTML, Handlebars etc... no dice.
